################################################################################
# mesos-slave:1.3.0
# Date: 02/20/2017
# Docker Version: 1.12.1-0~trusty
# Mesos Version: 1.1.0-2.0.107.ubuntu1404
#
# Description:
# Mesos slave container with docker-engine installed. With Docker moving away
# from a monolithic binary, docker-engine must now be installed within the
# container itself.
# Former author
# MAINTAINER Bob Killen / killen.bob@gmail.com / @mrbobbytables
################################################################################

FROM busybox

MAINTAINER Milan Baran / mbaran@pixelfederation.com / @mbaran


CMD ["/bin/sh","-c","sleep 20"]
